### ISSUE TITLE
check.cgi Enhancement

### ISSUE THREAD

**Issue by jlpoolen** [kellerben/dudle#1]
On a standard install when `check.cgi` is accessed to test what the status is of the build, the following appears:

    Some problem occured:
     - Localization will not work. You need to build the .mo files. Refer the README for details.

The README.txt file provides:
>    ...
>    4. If you want a language other than English, you need .mo files in order to use localisations. 
>       You have 2 possibilities:
>       a. Run this small script to fetch the files from the main server:

>            cd $DUDLE_INSTALLATION_PATH
>           for i in locale/??; do
>              wget -O $i/dudle.mo https://dudle.inf.tu-dresden.de/locale/`basename $i`/dudle.mo
>            done

>       b. Build them on your own. This requires libgettext-ruby-util, potool, and make to be installed.
>            sudo aptitude install libgettext-ruby-util potool make
>            make
    
I recommend the "Some problem occured: [sic]" be replaced with "If you want a language other than English, you will need a localization and therefore need ot build the .mo files.  Refer..."

**Comment by kellerben** [comment]
I changed the wording
