### ISSUE TITLE
create random adress by default, dont take the title for it

### ISSUE THREAD

**Issue by qwertele** [kellerben/dudle#106]
Hey there,
thanks for making the dudle.

I know people who use your dudle because they value their privacy. At the same time, they use very easy titles that other people might very well use, and are not aware of the privacy issue when that title becomes the adress.

I propose to randomly generate an adress, unless the user specifically says otherwise.

Thanks for reading!

**Comment by kellerben** [comment]
I think this is a good idea…

**Comment by kellerben** [comment]
implemented in 81093f5

**Comment by qwertele** [comment]
Thank you! (:
