### ISSUE TITLE
Dropdown menu for language choice

### ISSUE THREAD

**Issue by bkmgit** [kellerben/dudle#112]
The langauge choices are obscuring some of the information in the header. A dropdown menu is a cleaner approach. Something similar to [this](https://stackoverflow.com/questions/38909766/list-of-all-country-languages-for-dropdown-select-menu-html-form#38909979). Use [language icon](http://www.languageicon.org/) at the top of the dropdown menu.

**Comment by bkmgit** [comment]
Basic implementation can be found [here](https://github.com/bkmgit/dudle)  
Dropdown menu can be improved using Javascript, as explained [here](https://www.w3schools.com/howto/howto_css_dropdown_navbar.asp) and [here](https://www.w3schools.com/howto/howto_custom_select.asp)

**Comment by kellerben** [comment]
implemented in bb86354f2424168218bf69865421b34e0ce65f4d

**Comment by bkmgit** [comment]
Thanks for adding this. It may be helpful to use the language icon, since the phrase `change language` is not informative if it is in a language you do not know.
