### ISSUE TITLE
Hosted web site: Library gettext missing

### ISSUE THREAD

**Issue by SmartBulb67** [kellerben/dudle#114]
Thank you for providing a self-hosted alternative for Doodle.
I am just trying to get this running on a hosted web space (Strato PowerWeb), but with no luck currently.
When accessing the "check.cgi" I get the following message:

> Some problem occurred:
>
> - Some Library is missing:
>   cannot load such file -- gettext`
> Some System Info:
> Ruby Version: 1.9.3-p551
Followed by some environment information.

All other CGI scripts throw a "500 Internal Server Error".

Any ideas on this?

Best regards,
Daniel

**Comment by kellerben** [comment]
You have to install the ruby gettext library. Please read the README, it is written in the requirements section.
