### ISSUE TITLE
"Die Website ist nicht erreichbar"

### ISSUE THREAD

**Issue by AndreasKueck** [kellerben/dudle#133]
"Die Antwort von dudle.inf.tu-dresden.de hat zu lange gedauert."

Das wird angezeigt, wenn ich versuche, https://dudle.inf.tu-dresden.de/ aufzurufen.

**Comment by kellerben** [comment]
Danke für die Info. An der Uni gab es einen Stromausfall, der Server scheint noch nicht wieder hochgefahren zu sein :-(.
Ich bin dran jemanden zu erreichen.

**Comment by mradcke** [comment]
Gibt es hierzu schon etwas Neues?

**Comment by kellerben** [comment]
Leider noch nicht. Andere Webseiten sind auch noch nicht wieder da. Ich kann an der Hardware leider auch nicht machen und bin da auf die Mithilfe angewiesen…

**Comment by kellerben** [comment]
jetzt sollte alles wieder gehen!
