### ISSUE TITLE
HTTP 403 for the site regarding extensions examples

### ISSUE THREAD

**Issue by entomologe** [kellerben/dudle#143]
The link in README.md seems broken resp. forbidden: https://dud-poll.inf.tu-dresden.de/extensions/

I also like to ask if there are more options planned for the voting method which I regard as rather important (cf. https://de.wikipedia.org/wiki/Sozialwahltheorie#Eigenschaften_der_Sozialwahlverfahren )? Sadly I don't speak ruby yet, but it would be some worthwhile project for learning it I guess.

**Comment by kellerben** [comment]
More voting methods are not planned
