### ISSUE TITLE
Website not reachable

### ISSUE THREAD

**Issue by Knightmare85** [kellerben/dudle#156]
https://dud-poll.inf.tu-dresden.de/ Website is not reachable since a few days.

**Comment by mcmusic2** [comment]
Yes. I have the same experience. Is somebody working on it? Sould this be reported on another channel? The servers on 
https://betriebsstatus.zih.tu-dresden.de/?action=statistik-open 
all show green at this moment except backup. Working dud-poll websites are in heavy use by many parties. So a working server is most welcome ...

**Comment by mcmusic2** [comment]
They are working on it. See
https://betriebsstatus.zih.tu-dresden.de/
[Failure survey tool DuD-Poll]

**Comment by kellerben** [comment]
There was a power outage and now there is an issue at the server. They are on it to fix it, however, it seems to take longer than expected…

**Comment by kellerben** [comment]
up and running since Friday
