### ISSUE TITLE
css directory required?

### ISSUE THREAD

**Issue by jlpoolen** [kellerben/dudle#2]
I pull this project and placed it under /usr/local/src/dudle.

I then created a soft link to my cgi-bin directory:

>  ln -s /usr/local/src/dudle /var/www/localhost/cgi-bin/dudle

When I try to access `http://[SERVER]/cgi-bin/dudle/index.cgi`
I get the following error message:

>Internal Server Error

>The server encountered an internal error or misconfiguration and was unable to complete your request.

>Please contact the server administrator, root@localhost and inform them of the time the error occurred, and anything you might have done that may have caused the error.

>More information about this error may be available in the server error log.

Moreover, my apache's error log has:
> [Thu Nov 12 20:56:23 2015] [error] [client 192.168.1.2] /usr/local/src/dudle/dudle.rb:149:in `open': No such file or directory - ./css/ (Errno::ENOENT)
> [Thu Nov 12 20:56:23 2015] [error] [client 192.168.1.2] \tfrom /usr/local/src/dudle/dudle.rb:149:in `initialize'
> [Thu Nov 12 20:56:23 2015] [error] [client 192.168.1.2] \tfrom /var/www/localhost/cgi-bin/dudle/index.cgi:27:in `new'
> [Thu Nov 12 20:56:23 2015] [error] [client 192.168.1.2] \tfrom /var/www/localhost/cgi-bin/dudle/index.cgi:27:in `<main>'
> [Thu Nov 12 20:56:23 2015] [error] [client 192.168.1.2] Premature end of script headers: index.cgi

Line 149 has:
>	Dir.open("#{@basedir}/css/").each{|f|

Yet, the project directory has no `/css` directory.  There seems to be an assumption that there is a css directory which, in my installation, is not present.

Here's what is in my directory:

        themis dudle # ls -1
        about.cgi
        access_control.rb
        atom.rb
        authorization_required.cgi
        charset.rb
        check.cgi
        classic.css
        config_defaults.rb
        config_sample.rb
        customize.cgi
        customize.rb
        date_locale.rb
        default.css
        delete_poll.rb
        dudle.rb
        edit_columns.rb
        error.cgi
        example.cgi
        favicon.ico
        hash.rb
        history.rb
        html.rb
        index.cgi
        invite_participants.rb
        License
        locale
        log.rb
        Makefile
        not_found.cgi
        overview.rb
        participate.rb
        pollhead.rb
        poll.rb
        print.css
        README
        #README#
        timepollhead.rb
        timestring.rb
        vcs_bzr.rb
        vcs_git.rb
        vcs_test.rb
        themis dudle # 

There should either be a css directory, or the instruction ` Place this application into a directory where cgi-scripts are evaluated`  should be revised.

**Comment by jlpoolen** [comment]
My access log shows what is missing from the distribution:

     XX.XXX.XXX.XXX - - [12/Nov/2015:22:13:58 -0800] "POST /cgi-bin/dudle/ HTTP/1.1" 403 272
     XX.XXX.XXX.XXX - - [12/Nov/2015:22:15:12 -0800] "GET /cgi-bin/dudle/index.cgi HTTP/1.1" 200 3511
     XX.XXX.XXX.XXX  - - [12/Nov/2015:22:15:12 -0800] "GET /cgi-bin/dudle/default.css HTTP/1.1" 500 590
     XX.XXX.XXX.XXX  - - [12/Nov/2015:22:15:12 -0800] "GET /cgi-bin/dudle/classic.css HTTP/1.1" 500 590
     XX.XXX.XXX.XXX  - - [12/Nov/2015:22:15:12 -0800] "GET /cgi-bin/dudle/print.css HTTP/1.1" 500 590

This may help identify what should be in the .git repository?

**Comment by kellerben** [comment]
This was a problem coming from the transition from bzr
