### ISSUE TITLE
Creation of a New Dudle Fails

### ISSUE THREAD

**Issue by jlpoolen** [kellerben/dudle#4]
After bypassing Issues #2 and #3, I finally got a page (without benefit of css) that allowed me to create a new dudle.  When I clicked the "Create" button, the process errored out. 
![2015-11-12 21_54_50-dudle](https://cloud.githubusercontent.com/assets/227313/11139824/d39a45b2-8988-11e5-8be0-c50b7bf5bbc9.png)

I got this error:

    Forbidden

        You don't have permission to access /cgi-bin/dudle/ on this server.
        Apache Server at themis Port 80

My error log shows:

        [Thu Nov 12 21:54:30 2015] [error] [client 192.168.1.2] attempt to invoke directory as script: /var/www/localhost/cgi-bin/dudle/, referer: http://themis/cgi-bin/dudle/index.cgi

Yet, I do have permissions set on the directory for apache to write in:

        themis dudle # ls -la ../dudle
        total 308
        drwxrwxr-x  7 apache  apache   4096 Nov 12 21:38 .
        drwxrwxrwx 61 root    root     4096 Nov 12 09:03 ..
        -rwxrwxr-x  1 apache  apache   2104 Nov 12 04:20 about.cgi
        -rwxrwxr-x  1 apache  apache   7197 Nov 12 04:20 access_control.rb
        -rwxrwxr-x  1 apache  apache   2477 Nov 12 04:20 atom.rb
        -rwxrwxr-x  1 apache  apache   2542 Nov 12 04:20 authorization_required.cgi
        -rwxrwxr-x  1 apache  apache     64 Nov 12 04:20 .bzrignore
        -rwxrwxr-x  1 apache  apache   2881 Nov 12 04:20 charset.rb
        -rwxrwxr-x  1 apache  apache   2804 Nov 12 04:20 check.cgi
        -rwxrwxr-x  1 apache  apache   5115 Nov 12 04:20 classic.css
        -rwxrwxr-x  1 apache  apache   2278 Nov 12 04:20 config_defaults.rb
        -rwxrwxr-x  1 apache  apache   5275 Nov 12 04:20 config_sample.rb
        drwxr-xr-x  2 root    root     4096 Nov 12 21:37 css
        drwxr-xr-x  2 root    root     4096 Nov 12 21:36 .css
        lrwxrwxrwx  1 apache  apache     12 Nov 12 04:20 customize.cgi -> customize.rb
        -rwxrwxr-x  1 apache  apache   4246 Nov 12 04:20 customize.rb
        -rwxrwxr-x  1 apache  apache  13024 Nov 12 04:20 date_locale.rb
        -rwxrwxr-x  1 apache  apache   6825 Nov 12 04:20 default.css
        -rwxrwxr-x  1 apache  apache   4354 Nov 12 04:20 delete_poll.rb
        -rwxrwxr-x  1 apache  apache   8247 Nov 12 04:20 dudle.rb
        -rwxrwxr-x  1 apache  apache   4058 Nov 12 04:20 edit_columns.rb
        -rwxrwxr-x  1 apache  apache   3383 Nov 12 04:20 error.cgi
        -rwxrwxr-x  1 apache  apache   2493 Nov 12 04:20 example.cgi
        drwxr-xr-x  2 root    root     4096 Nov 12 21:38 extensions
        -rwxrwxr-x  1 apache  apache   1406 Nov 12 04:20 favicon.ico
        drwxrwxr-x  7 apache  apache   4096 Nov 12 20:58 .git
        -rwxrwxr-x  1 apache  apache   2684 Nov 12 04:20 hash.rb
        -rwxrwxr-x  1 apache  apache   2095 Nov 12 04:20 history.rb
        -rwxrwxr-x  1 apache  apache    477 Nov 12 04:20 .htaccess
        -rwxrwxr-x  1 apache  apache   4370 Nov 12 04:20 html.rb
        -rwxrwxr-x  1 apache  apache   4698 Nov 12 04:20 index.cgi
        -rwxrwxr-x  1 apache  apache   1964 Nov 12 04:20 invite_participants.rb
        -rw-r--r--  1 apache  apache      0 Nov 12 21:04 .koSai8ahye9shoTh
        -rwxrwxr-x  1 apache  apache  32387 Nov 12 04:20 License
        drwxrwxr-x 13 apache  apache   4096 Nov 12 04:20 locale
        -rwxrwxr-x  1 apache  apache   7974 Nov 12 04:20 log.rb
        -rwxrwxr-x  1 apache  apache   2065 Nov 12 04:20 Makefile
        -rwxrwxr-x  1 apache  apache   2325 Nov 12 04:20 not_found.cgi
        -rwxrwxr-x  1 apache  apache   2173 Nov 12 04:20 overview.rb
        -rwxrwxr-x  1 apache  apache   2644 Nov 12 04:20 participate.rb
        -rwxrwxr-x  1 apache  apache   4959 Nov 12 04:20 pollhead.rb
        -rwxrwxr-x  1 apache  apache  19161 Nov 12 04:20 poll.rb
        -rwxrwxr-x  1 apache  apache   3860 Nov 12 04:20 print.css
        -rwxrwxr-x  1 apache  apache   3537 Nov 12 05:00 README
        lrwxrwxrwx  1 root    root       27 Nov 12 21:04 .#README -> root@themis.4361:1447347113
        -rwxr-xr-x  1 jlpoole jlpoole  3537 Nov 12 21:05 #README#
        -rwxrwxr-x  1 apache  apache  15216 Nov 12 04:20 timepollhead.rb
        -rwxrwxr-x  1 apache  apache   3276 Nov 12 04:20 timestring.rb
        -rwxrwxr-x  1 apache  apache   2296 Nov 12 04:20 vcs_bzr.rb
        -rwxrwxr-x  1 apache  apache   2777 Nov 12 04:20 vcs_git.rb
        -rwxrwxr-x  1 apache  apache   2687 Nov 12 04:20 vcs_test.rb
        themis dudle # 

I also tried creating a "Normal Poll" rather than an "Event Schedule Poll" and got the same error message.

**Comment by jlpoolen** [comment]
I should add the the directory `/usr/local/src/dudle` does have apache:apache as the owner and ability to to write therein:

      themis src # pwd
     /usr/local/src
     themis src # ls -la
     ...
      drwxrwxr-x  7 apache  apache       4096 Nov 12 21:38 dudle
     ...

**Comment by jlpoolen** [comment]
The source for the form shows:

      <form method='post' action='.'>

Presumably that is "index.cgi".  But does that have to specified as a default value within Apache?

**Comment by jlpoolen** [comment]
I went ahead and modified index.cgi so that the form called itself.  The line was modified to:

     <form method='post' action='index.cgi'>

And then when I clicked the "Create" button, I got an error message:

     Internal Server Error

     The server encountered an internal error or misconfiguration and was unable to complete your request.

     Please contact the server administrator, root@localhost and inform them of the time the error occurred, and anything you might have done that may have caused the error.

     More information about this error may be available in the server error log.


The error logs shows:
         udle/index.cgi
        [Thu Nov 12 22:21:42 2015] [error] [client XXX.XXX.XXX.XXX] /usr/local/src/dudle/dudle.rb:130:in `initialize': , referer: http://themis/cgi-bin/dudle/index.cgi
        [Thu Nov 12 22:21:42 2015] [error] [client  XXX.XXX.XXX.XXX] undefined method `name' for false:FalseClass (NoMethodError), referer: http://themis/cgi-bin/dudle/index.cgi
        [Thu Nov 12 22:21:42 2015] [error] [client  XXX.XXX.XXX.XXX] \tfrom /var/www/localhost/cgi-bin/dudle/test1/edit_columns.cgi:34:in `new', referer: http://themis/cgi-bin/dudle/index.cgi
        [Thu Nov 12 22:21:42 2015] [error] [client  XXX.XXX.XXX.XXX] \tfrom /var/www/localhost/cgi-bin/dudle/test1/edit_columns.cgi:34:in `<main>', referer: http://themis/cgi-bin/dudle/index.cgi
        [Thu Nov 12 22:21:42 2015] [error] [client  XXX.XXX.XXX.XXX] Premature end of script headers: edit_columns.cgi, referer: http://themis/cgi-bin/dudle/index.cgi

**Comment by kellerben** [comment]
If you install it into a /cgi-bin/ directory, then please ensure, that only files with the .cgi extension are executed. Otherwise It will try to interpret .css files the favicon.ico etc… as scripts and execute them.
(this will solve your css problem)

I recommend to install dudle to another directory and explicitly enable .cgi-execution only…

The error you posted is not your problem. Something went wrong when creating the poll. Please check if you have a directory named with the poll-name in your dudle-root which has a proper git repo inside. E.g.:
you have a directory:
/usr/local/src/dudle/my-poll/
with 
/usr/local/src/dudle/my-poll/.git

**Comment by jlpoolen** [comment]
I merged your changes into my branch and updated my local copy which I have staged at `/usr/local/src/dudle`.   I then created a softlink for the server under `/var/www/localhost/htdocs`:

     ln -s /usr/var/src/dudle /var/www/localhost/htdocs/dudle

I also had to modify my apache server to activate cgi processing under the /htdocs.  (Having cgi executables outside of the traditional /cgi-bin/ tree seems to run against Apache's attempt to isolate executable into a single tree, to wit: [apache server root]/cgi-bin.)  Any rate, I modified /etc/apache2/vhosts.d/default_vhosts.include:

      <Directory "/var/www/localhost/htdocs/dudle">
            Options FollowSymLinks Indexes
        #AllowOverride None

        Order allow,deny
        Allow from all

I than visited the site and the page appears fine with the .css feature working.  However, when I try to create an event, the return page is an error:

     Internal Server Error

     The server encountered an internal error or misconfiguration and was unable to complete your request.

Apache's log has:

    [Thu Nov 19 04:33:50 2015] [error] [client 192.168.1.2] /usr/local/src/dudle/dudle.rb:130:in `initialize', referer: http://themis/dudle/
    [Thu Nov 19 04:33:50 2015] [error] [client 192.168.1.2] : undefined method `name' for false:FalseClass (NoMethodError), referer: http://themis/dudle/
    [Thu Nov 19 04:33:50 2015] [error] [client 192.168.1.2] \tfrom /var/www/localhost/htdocs/dudle/test17/edit_columns.cgi:34:in `new', referer: http://themis/dudle/
    [Thu Nov 19 04:33:50 2015] [error] [client 192.168.1.2] \tfrom /var/www/localhost/htdocs/dudle/test17/edit_columns.cgi:34:in `<main>', referer: http://themis/dudle/
    [Thu Nov 19 04:33:50 2015] [error] [client 192.168.1.2] Premature end of script headers: edit_columns.cgi, referer: http://themis/dudle/
    [Thu Nov 19 04:33:50 2015] [error] [client 192.168.1.2] File does not exist: /var/www/localhost/htdocs/error.cgi, referer: http://themis/dudle/


            AddHandler cgi-script .cgi .rb
    </Directory>

**Comment by jlpoolen** [comment]
Here's a link to the code where the failure occurs.  I'm wondering if the failure is occurring at:

     @table = YAML::load(VCS.cat(self.revision, "data.yaml"))

https://github.com/kellerben/dudle/blob/ea0c4bcf4a5cb02533c5b1c6c03f827578689204/dudle.rb#L128-L130

It may be that YAML::load is not a standard package including with ruby?
Here are the contents of the test17 directory:

    themis dudle # ls -la test17
    total 16
    drwxr-xr-x  3 apache apache 4096 Nov 19 04:33 .
    drwxrwxr-x 23 apache apache 4096 Nov 19 04:33 ..
    lrwxrwxrwx  1 apache apache   20 Nov 19 04:33 access_control.cgi -> ../access_control.rb
    lrwxrwxrwx  1 apache apache   10 Nov 19 04:33 atom.cgi -> ../atom.rb
    lrwxrwxrwx  1 apache apache   15 Nov 19 04:33 customize.cgi -> ../customize.rb
    -rw-rw----  1 apache apache  123 Nov 19 04:33 data.yaml
    lrwxrwxrwx  1 apache apache   17 Nov 19 04:33 delete_poll.cgi -> ../delete_poll.rb
    lrwxrwxrwx  1 apache apache   18 Nov 19 04:33 edit_columns.cgi -> ../edit_columns.rb
    drwxr-xr-x  6 apache apache 4096 Nov 19 04:33 .git
    lrwxrwxrwx  1 apache apache   13 Nov 19 04:33 history.cgi -> ../history.rb
    -rw-r--r--  1 apache apache    0 Nov 19 04:33 .htaccess
    -rw-r--r--  1 apache apache    0 Nov 19 04:33 .htdigest
    lrwxrwxrwx  1 apache apache   17 Nov 19 04:33 index.cgi -> ../participate.rb
    lrwxrwxrwx  1 apache apache   25 Nov 19 04:33 invite_participants.cgi -> ../invite_participants.rb
    -rw-r--r--  1 apache apache    0 Nov 19 04:33 last_read_access
    lrwxrwxrwx  1 apache apache   14 Nov 19 04:33 overview.cgi -> ../overview.rb
    themis dudle #

**Comment by jlpoolen** [comment]
There seem to be 2 errors happening here. 1) the failure at line https://github.com/kellerben/dudle/blob/ea0c4bcf4a5cb02533c5b1c6c03f827578689204/dudle.rb#L130  and 2) the `error.cgi` not being found.

For number two, in subdirectory `test17` there is a link:

      lrwxrwxrwx  1 root   root     12 Nov 19 05:29 error.cgi -> ../error.cgi

but the log shows that it is trying to find error.cgi under the root directory `\` instead of under `\dudle`.

**Comment by jlpoolen** [comment]
I've determined that YAML is included in my ruby:

     themis dudle # ruby -v 
     ruby 2.0.0p645 (2015-04-13 revision 50299) [x86_64-linux]
     themis dudle # 

So, what is triggering the error is that the object `@table` evaluates to false rather than holding the data that was to be read.  The file is there and apache has permissions to read it:

    themis test17 # ls -la data.yaml
    -rw-rw---- 1 apache apache 123 Nov 19 04:33 data.yaml
    themis test17 # cat data.yaml
    # This is a dudle poll file
    --- !ruby/object:Poll
    name: test17
    head: !ruby/object:PollHead
      data: {}
    data: {}
    comment: []
    themis test17 #

**Comment by jlpoolen** [comment]
The problem seems to arising within this project's VCS class:

https://github.com/kellerben/dudle/blob/ea0c4bcf4a5cb02533c5b1c6c03f827578689204/vcs_git.rb#L48-L50

My unfamiliarity with ruby and git are making this difficult to sort out.  What would be a git command to run against the file `data.yaml` to simulate what the `cat` method is suppose to do?

**Comment by jlpoolen** [comment]
For anyone else trying to get an understanding, I'm finding this reference to be helpful re: git:

https://git-scm.com/book/en/v2/Git-Internals-Git-Objects

**Comment by kellerben** [comment]
I think the problem is, that this command failed:
https://github.com/kellerben/dudle/blob/ea0c4bcf4a5cb02533c5b1c6c03f827578689204/vcs_git.rb#L68

please give me the output of the following:

    cd /var/www/localhost/htdocs/dudle
    sudo -u apache git log

**Comment by jlpoolen** [comment]
themis test17 # cd /var/www/localhost/htdocs/dudle
    themis dudle # sudo -u apache git log
    bash: sudo: command not found
    themis dudle # su apache
    This account is currently not available.
    themis dudle # 

The account apache does not allow you to login -- for security reasons.
I therefore modified my apache to execute perl scripts in this directory:

    <Directory "/var/www/localhost/htdocs/dudle">
            Options FollowSymLinks Indexes
        #AllowOverride None

        Order allow,deny
        Allow from all

            AddHandler cgi-script .cgi .pl
    </Directory>
and then created this perl script:

    #!/usr/bin/perl

    use strict;
    use warnings;
    use CGI;

    my $q = new CGI;

    print $q->header;
    chdir "/var/www/localhost/htdocs/dudle";

    my $cmd = "git log";
    my $results = `$cmd`;
    print $q->p("results"), $q->p($results);

I have the results (for 2 weeks) at: http://pastebin.com/XBe19y5W

**Comment by jlpoolen** [comment]
I tried in a root shell `git log` in the main directory and viewed results.  When I tried in the test17 directory, git croaked:

     themis test17 # git log
     fatal: bad default revision 'HEAD'
     themis test17 #

It looks like the git repository is not being created properly or that during creation something broke so the repository is broken.

**Comment by kellerben** [comment]
Have you tried this already?
https://github.com/kellerben/dudle/blob/ea0c4bcf4a5cb02533c5b1c6c03f827578689204/README#L36-L40

If this does not help, can you please try the following:

	diff --git a/vcs_git.rb b/vcs_git.rb
	index 13b0b3a..fb9dcdd 100644
	--- a/vcs_git.rb
	+++ b/vcs_git.rb
	@@ -65,7 +65,7 @@ class VCS
			File.open(tmpfile,"w"){|f|
				f<<comment
			}
	-		ret = runcmd(GITCMD, "commit", "-a", "-F", tmpfile)
	+		ret = runcmd(GITCMD, "commit", "-a", "-F", tmpfile, "--author='apache <apache@localhost>'")
			File.delete(tmpfile)
			ret
		end

**Comment by jlpoolen** [comment]
At your suggestion, I modified Apache's configuration thusly:
    <Directory "/var/www/localhost/htdocs/dudle">
            Options FollowSymLinks Indexes
        #AllowOverride None
        SetEnv GIT_AUTHOR_NAME="apache"
        SetEnv GIT_AUTHOR_EMAIL=foo@example.org
        SetEnv GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"
        SetEnv GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"
        Order allow,deny
        Allow from all

            AddHandler cgi-script .cgi .pl
    </Directory>

And it worked!

Thank you.

**Comment by kellerben** [comment]
I added a new check to check.cgi. Would be nice if you test this (without the setenv things)
