### ISSUE TITLE
Ruby "env"

### ISSUE THREAD

**Issue by jlpoolen** [kellerben/dudle#5]
The `*.cgi` scripts have a command line for the web server to invoke Ruby with:

     #!/usr/bin/env ruby

Gentoo does not install Ruby with the "env" as standard, instead it is offered as an option in `dev-ruby/nenv`.  Consequently, on a standard install the cgi would invoke Ruby with `#!/usr/bin/ruby`.

The instructions might alert prospective installer that the "env" feature of ruby is required since I'm guessing that "env" is not a standard installation item for Ruby.  This may only be Gentoo related?

**Comment by kellerben** [comment]
env is no ruby feature, it is a tool which interprets the current environment variables and runs ruby whereever it is installed. You have to install env of course (in /usr/bin/env) but then you can install ruby whereever you want (e.g. in /usr/local/bin/ruby). This directory has to be in the PATH variable of apache…
