### ISSUE TITLE
NameError: uninitialized constant VCS

### ISSUE THREAD

**Issue by jGleitz** [kellerben/dudle#56]
I installed dudle and get the following output by `check.cgi`:

```
Some problem occured. Please contact the developer:
#<NameError: uninitialized constant VCS>
```

Surely, I have missed something while installing. However, I re-checked the instructions 3 times now and cannot find my mistake. `gem install vcs` does not help. The Error Log is empty.

**Comment by kellerben** [comment]
it somehow didn't loaded vcs_git.rb. I don't understand, why this is the case… Did you modified config_defaults.rb? (you should leave this intact!)

Can you do 2 things:
1. Send me the output of check.cgi with the updated repo (I just added 1 line)
2. do a git checkout 07c331e and try the check.cgi with this version

**Comment by jGleitz** [comment]
I forgot to comment that it’s now working for me.

The solution was to install `ruby-gettext` so I could run `make`.

I thought running `make` was optional and didn’t think of trying that before.

**Comment by kellerben** [comment]
I doubt, that ruby-gettext was the solution for the VCS problem…
