### ISSUE TITLE
Translation for Norwegian done, how to contribute

### ISSUE THREAD

**Issue by geolr** [kellerben/dudle#66]
Hi, I have made rudimentary norwegian translation (no_nb). Not sure how to submit (git-newbie, would this be a pull-request?). Find it here: https://github.com/geolr/dudle_norwegian_nb/blob/master/dudle%20-%20no-nb.po

Not a native speaker, but german-norwegian and a couple of years living in Norway help a lot. 

Thanks for great work, looking forward to try the nextcloud-integration :-)

**Comment by geolr** [comment]
spotted already a question: There is a line in english about legal characters: ..."dashes". In german i have seen it says: dash (minus) or underscore. Which is correct and should be in the translation?

**Comment by kellerben** [comment]
You can open a pull-request.

The correct translation is the underscore

**Comment by kellerben** [comment]
I integrated your file… Thank you for your contribution!
