### ISSUE TITLE
Error when trying to create dudle

### ISSUE THREAD

**Issue by unclesam87** [kellerben/dudle#68]
The scripts open in Nextcloud, but when i try to create an dudle it crashes and shows me that message:

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Apache/2.4.18 (Ubuntu) Server at subdomain.maindomain.de Port 443

**Comment by kellerben** [comment]
I have no idea about the nextcloud integration, maybe you want to open an issue here https://github.com/mroi/nextcloud-dudle?

However, as the error message says:
> More information about this error may be available in the server error log.

**Comment by mroi** [comment]
Hi, I’m the author of the Nextcloud integration. From time to time, I see these Internal Server Errors too, but I have not gotten around to debug that. It does not appear to be reproducible. However, for me, the poll is still created correctly so just reloading gets rid of the error for me.

**Comment by kellerben** [comment]
You can send me the contents of error.log, maybe I see the problem…

**Comment by unclesam87** [comment]
Hey, 
sorry for my late response, i had to fix some bigger problems on other jobs.

I had to reinstall the whole nextcloud, bc of a bigger crash. 
Now i have the problem that it wont even start, it just shows a code when i click on it. Any Ideas? 


To the old problems: can it be that the errors had something to do with that our site uses https ?

**Comment by kellerben** [comment]
cgi is not evaluated on your server.
