### ISSUE TITLE
$conf.siteurl + POLLURL

### ISSUE THREAD

**Issue by ukcb** [kellerben/dudle#73]
I've defined a $conf.siteurl. After creating a survey I see on the page overview.cgi only the values of $conf.siteurl without a POLLURL. I can not distribute the complete URL (with POLLURL). Please fix that, thank you very much.

**Comment by JayDee2202** [comment]
As well after saving an entry I get redirected to that URL so users land at the start page. So there is also a reference to the POLLURL missing.

**Comment by mguentner** [comment]
Is there any known fix? Maybe an enhanced `overview.rb`?

**Comment by mguentner** [comment]
Fixed it directly in `config.rb`!

Just use this:

```ruby
$conf.siteurl = "https://dudle.example.com#{$cgi.script_name.gsub(/[^\/]*$/,"")}"
```

The script_name magic is from `config_defaults.rb`

**Comment by ukcb** [comment]
Thank you. This works perfectly. Could be used as an example for `config_sample.rb`.

**Comment by kellerben** [comment]
added a hint in 7d396c7
