### ISSUE TITLE
Problem creating a Poll

### ISSUE THREAD

**Issue by frankpau** [kellerben/dudle#77]
Hi,

i got dudle running on my centos 7 system based on the sources on github.
when i try to create a Poll by entering a name for the poll and press the create button i get the following error message:

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at root@localhost to inform them of the time this error occurred, and the actions you performed just before this error.
More information about this error may be available in the server error log.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

in the ssl_error.log i see the following:

[Wed Sep 20 14:50:00.155222 2017] [cgi:error] [pid 24828] [client :46647] AH01215: /var/www/dudle/dudle.rb:130:in `initialize': undefined method `name' for false:FalseClass (NoMethodError), referer: https://<URL>:9443/dudle/
[Wed Sep 20 14:50:00.155331 2017] [cgi:error] [pid 24828] [client :46647] AH01215: \tfrom /var/www/dudle/ww4/edit_columns.cgi:34:in `new', referer: https://>URL>:9443/dudle/
[Wed Sep 20 14:50:00.155374 2017] [cgi:error] [pid 24828] [client :46647] AH01215: \tfrom /var/www/dudle/ww4/edit_columns.cgi:34:in `<main>', referer: https://>URL>:9443/dudle/
[Wed Sep 20 14:50:00.163160 2017] [cgi:error] [pid 24828] [client :46647] End of script output before headers: edit_columns.cgi, referer: https://<URL>:9443/dudle/

in the dudle Directory i see a directory with the name i gave the Poll.
Referring to https://github.com/kellerben/dudle/issues/4
i tried "sudo -u apache git log" in this directory:

fatal: bad default revision 'HEAD'

I also put the Variables from the README into my httpd dudle.conf:
Alias /dudle "/var/www/dudle"
<Directory /var/www/dudle>
     Options +ExecCGI
     AllowOverride All
     SetEnv GIT_AUTHOR_NAME="apache"
     SetEnv GIT_AUTHOR_EMAIL=foo@example.org
     SetEnv GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"
     SetEnv GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"
     Order allow,deny
     Allow from all
</Directory>

This didn't solve the problem.

Any help is appreciated.

Regards
Frank

Any Idea ?

**Comment by bkmgit** [comment]
Hi,
Not sure of the steps you followed, but may need to build some of the packages for Cent OS 7 by hand to get up to date versions that are compatible with what dudle requires. Instructions for a Fedora 26 build are at https://github.com/bkmgit/dudle-docker/blob/master/Dockerfile

**Comment by kellerben** [comment]
can you please check if the directory /var/www/dudle/ww4/.git exists?

**Comment by frankpau** [comment]
Von meinem Huawei-Mobiltelefon gesendetSure it dies.AS i wrote, gut in this directory doesn't seem to be OK.Regards frank-------- Originalnachricht --------Betreff: Re: [kellerben/dudle] Problem creating a Poll (#77)Von: Benjamin Kellermann An: kellerben/dudle Cc: frankpau ,Author can you please check if the directory /var/www/dudle/ww4/.git exists?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/kellerben/dudle","title":"kellerben/dudle","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/kellerben/dudle"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kellerben in #77: can you please check if the directory /var/www/dudle/ww4/.git exists?"}],"action":{"name":"View Issue","url":"https://github.com/kellerben/dudle/issues/77#issuecomment-330978178"}}}

**Comment by frankpau** [comment]
Hi,

i just checked the steps in the docker instructions and except from the fast_gettext gem i installed everything.
i also compiled potool from the sources.
As is said , i can access the start page but when i try to create a poll, the directory is created in the dudle path, but the error from the initial post shows up.
i think there is a problem with the git repository.

Regards
Frank

**Comment by bkmgit** [comment]
Docker container runs ok for me with current git sources (also with last few commits as well), though not currently setup for https. May need to change folder permissions. Have you tried older commits?

**Comment by frankpau** [comment]
Hi,
i just updated all the packages from the docker instructions and renewed my self signed certificate and not it works.
to be honest i have no idea what made it work.
nevertheless, i came accross one thing where i don't know if its wanted or not:
if i create a poll with access restrictions and the restricted user accesses the poll , he can create (and delete) new polls.

One other Thing: is it possible to only publish the Poll itself , for instance in a frame on another website, without any menu ?

Regards
Frank
