### ISSUE TITLE
Delete All Votes

### ISSUE THREAD

**Issue by nwhansen** [kellerben/dudle#79]
We have been looking for a poll software to replace Doodle, and have found your software and site. I am not familiar with Ruby and so a pull request for this particular change is not easy, at least in a timely manor.  The feature i would really love is the ability to delete all votes on a given poll.

We reuse the same poll for deciding what board games to play, and keeping the columns but not the votes would be fantastic for our use case.

**Comment by kellerben** [comment]
It is difficult to implement this on a general basis as there are different types of polls (which all must be handled differently). Maybe if I implement #10, it would be an option to use this feature…
