### ISSUE TITLE
Please consider making a new release

### ISSUE THREAD

**Issue by josch** [kellerben/dudle#82]
Hi,

I was pleased to see this project still alive after all these years and I finally got around to package it for Debian.

Though I noticed that the latest version 1.1 is from 2014 and 107 commits have happened since then. Especially commits like 853dc8b41f are quite important to have. Would you consider making a new release?

Thanks!

cheers, josch

**Comment by josch** [comment]
Another thought I had was the following:

I would also very much like to offer the extensions in Debian. I think those features are the ones that really distinguish dudle from all other poll software. So it would be nice if you could make versioned releases of the extensions as well.

Without versioned releases, we have to artificially create a version number which is usually done by combining the date of the last commit with the short commit hash for versions that look like this: `0.0~git20170124.0.f94ae5e-2+b1` Since this is quite ugly, I'd like to avoid that. One way of avoiding it is, if you would just pick a version number and make a release.

But for the extensions and the css repositories there is an alternative. Instead of versioning each of these repositories, which you may find tedious, you could also make the repositories git submodules of the main dudle reposiitory. In that case, the content of the extensions and css repositories would be part of the dudle release tarball every time that you make a dudle release. This approach would also mean less work for me because then I only have a single dudle source package that includes the code for all the extensions in contrast to having to maintain seven individual packages in Debian (the main dudle package plus five extensions plus the css package). This approach might also prove beneficial to your users because then it might be easier for them to add extensions to their dudle installations by just initializing the right git submodule. The code would then also automatically already be in the right spot.

Just tell me what you would like to do. As I said, it will even work for Debian without you making releases or using git submodules. As soon as I have your response I'll make the upload to Debian, because the package is ready. :)

Thanks!

cheers, josch

**Comment by kellerben** [comment]
the participate extension should be loaded first (that's why I named it 10-participate)
The anonymous-extension is incompatible to the others. That's why i have them in separate directories (dudle.inf.tu-dresden.de and dudle.inf.tu-dresden.de/anonymous)
However, the incompatibility is on client side (jquery vs. prototype)

I would propose to package 2 Packages. dudle-extension-anonymous and dudle-extension-common which are in conflict. 

On my servers I already have the extensions as git submodules. I will think about a solution to the versioning after christmas…

**Comment by josch** [comment]
Hrm... then indeed it does not make sense to have all the extensions included as submodules altogether. Would it be lots of work to let the extensions co-exist?

Otherwise, your suggestion to create a dudle-extension-anonymous and a dudle-extension-common package sounds sensible.

Thanks and happy holidays!

**Comment by kellerben** [comment]
just tagged dudle with v1.3 and all extensions with 1.0
anonymous is still incompatible with the others, participate is required for symcrypt, asymcrypt and gpgauth
I will keep an eye on compatibility as long as I do not change to v2
