### ISSUE TITLE
Extension ordering/conflicts?

### ISSUE THREAD

**Issue by josch** [kellerben/dudle#83]
Hi,

putting all extensions in the extensions directory produces the following error:

```
/var/lib/dudle/extensions/anonymous/main.rb:22:in `initialize': wrong number of arguments (given 0, expected 1) (ArgumentError)
	from /var/lib/dudle/extensions/asymcrypt/main.rb:21:in `new'
	from /var/lib/dudle/extensions/asymcrypt/main.rb:21:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/dudle/dudle.rb:280:in `block in out'
	from /var/lib/dudle/dudle.rb:277:in `each'
	from /var/lib/dudle/dudle.rb:277:in `out'
	from /var/lib/dudle/another_one/index.cgi:78:in `<main>'
```

I'm not very familiar with ruby but the culprit might be that the class `Extension` is defined by the `participate` as well as by the `anonymous` extension.

If the extensions conflict, could this be documented somewhere?

Or maybe they can be made non-conflicting?

Or maybe this is about in which order they get evaluated?

Thanks!

cheers, josch

**Comment by kellerben** [comment]
the participate extension should be loaded first (that's why I named it 10-participate)

**Comment by josch** [comment]
Maybe that should be documented somewhere? It is also not obvious (at least to me) that loading of extensions happens in alphametical order. So this should maybe also be documented?

**Comment by josch** [comment]
Also, even after renaming the participate directory, the error I posted above remains. So the extensions do not only conflict in their javascript at client side but also at the backend.

**Comment by kellerben** [comment]
added a comment to the README in 924af51
