### ISSUE TITLE
edit_columns.cgi is resulting in an error

### ISSUE THREAD

**Issue by Medienbecken** [kellerben/dudle#95]
Hello,
I'm running dudle on a ubuntu server vm. The homepage with the "Neue Umfrage erstellen" form (German localisation) is displayed correctly and the check.cgi says: "Your environment seems to be installed correctly!". However, when I try to create a new poll, I'm getting dudles error message.
Does anyone have any suggestions what to look for or where to find out more about what i causing the error.

Thank you,
Benjamin

**Comment by kellerben** [comment]
Please paste a more detailed error message and the output of your apache error.log

**Comment by Medienbecken** [comment]
First of all thanks for the fast response and for pointing to apaches error.log!

Here is the last error it reported there:

[Wed May 30 09:01:06.955504 2018] [cgi:error] [pid 1341] [client 192.168.56.1:58346] AH01215: /var/www/cgi-bin/dudle.rb:130:in `initialize': undefined method `name' for false:FalseClass (NoMethodError): /var/www/cgi-bin/kaffeesorte/edit_columns.cgi, referer: http://192.168.56.105/
[Wed May 30 09:01:06.955546 2018] [cgi:error] [pid 1341] [client 192.168.56.1:58346] AH01215: \tfrom /var/www/cgi-bin/kaffeesorte/edit_columns.cgi:34:in `new': /var/www/cgi-bin/kaffeesorte/edit_columns.cgi, referer: http://192.168.56.105/
[Wed May 30 09:01:06.955569 2018] [cgi:error] [pid 1341] [client 192.168.56.1:58346] AH01215: \tfrom /var/www/cgi-bin/kaffeesorte/edit_columns.cgi:34:in `<main>': /var/www/cgi-bin/kaffeesorte/edit_columns.cgi, referer: http://192.168.56.105/
[Wed May 30 09:01:06.956576 2018] [cgi:error] [pid 1341] [client 192.168.56.1:58346] End of script output before headers: edit_columns.cgi, referer: http://192.168.56.105/

I didn't think of this log file because I was not getting an server error but the dudle error page instead.

**Comment by kellerben** [comment]
is there a directory /var/www/cgi-bin/kaffeesorte/.git ?
what happens if you enter:
```sh
cd /var/www/cgi-bin/kaffeesorte
ls -l
sudo -u www-data git log
sudo -u www-data git show HEAD:data.yaml
```

**Comment by Medienbecken** [comment]
.git exists.
... git log     shows an error about the branch 'master' not having any commits
... git show HEAD:data.yaml     prints Invalid object name 'HEAD'

My git game is not the best but did I do anything wrong while cloning?

Thanks again,
Benjamin

**Comment by kellerben** [comment]
This git directory should be created by the poll-creation script, therefore there went something wrong. Can you give me the output of the following commands:
```sh
cd /var/www/cgi-bin/
git log --oneline -n1
ls -la kaffeesorte/
```
Have you created the poll kaffeesorte **after** ``check.cgi`` executed correctly?

**Comment by Medienbecken** [comment]
The output is fa661ef and its saying more debug info in check.cgi. That still says your system seems to be installed correctly...

I'm not 100% sure when I created that specific poll, but I tried making new polls a few times and there are always errors.

The output of the directory listing can be seen in the attached screenshot.
![dudle_kaffeesorte](https://user-images.githubusercontent.com/6402002/40959255-72bef7ce-689c-11e8-8ef0-692b8ffad057.png)

**Comment by kellerben** [comment]
I have no idea why this happened. Something went wrong when creating the poll, i.e. it should create a git-repository inside the poll-directory. However, this fails. In the check.cgi, I create a git repository as well should fail then as well. I have no idea why it is working there and not in the poll-creation phase…

**Comment by Medienbecken** [comment]
I try a clean reinstall and let you know if it works.

**Comment by Medienbecken** [comment]
It seems to be some sort of misconfiguration on my server. Simply removing all files and cloning the repo again leads to similar results.
I'm setting up a debian system to see if that brings me any further.

**Comment by Medienbecken** [comment]
The debian server is now set up and Dudle is working. I have no clue why it didn't like my ubuntu machine.

None the less thank you for your support! Now that it's working I can finally start to configure and test the actual software.
