### ISSUE TITLE
Internal Server Error - when create a schedule

### ISSUE THREAD

**Issue by ds2k5** [kellerben/dudle#97]
Hello,
I try to get Dudle run on a Ubuntu 18.04 Server.

But got this error if wanna create a schedule

> 
> Internal Server Error
> 
> The server encountered an internal error or misconfiguration and was unable to complete your request.
> 
> Please contact the server administrator at webmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error.
> 
> More information about this error may be available in the server error log.
> 
> Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.
> 

But the Directory of the "ScheduleName" will created.

drwxr-xr-x  3 www-data www-data  4096 Jul 12 05:29 TEST2

```
root@dudle:/var/www/dudle/TEST2# ls -lathr
total 16K
lrwxrwxrwx 1 www-data www-data   14 Jul 12 05:29 overview.cgi -> ../overview.rb
lrwxrwxrwx 1 www-data www-data   25 Jul 12 05:29 invite_participants.cgi -> ../invite_participants.rb
lrwxrwxrwx 1 www-data www-data   17 Jul 12 05:29 index.cgi -> ../participate.rb
lrwxrwxrwx 1 www-data www-data   13 Jul 12 05:29 history.cgi -> ../history.rb
lrwxrwxrwx 1 www-data www-data   18 Jul 12 05:29 edit_columns.cgi -> ../edit_columns.rb
lrwxrwxrwx 1 www-data www-data   17 Jul 12 05:29 delete_poll.cgi -> ../delete_poll.rb
lrwxrwxrwx 1 www-data www-data   15 Jul 12 05:29 customize.cgi -> ../customize.rb
lrwxrwxrwx 1 www-data www-data   10 Jul 12 05:29 atom.cgi -> ../atom.rb
lrwxrwxrwx 1 www-data www-data   20 Jul 12 05:29 access_control.cgi -> ../access_control.rb
-rw-r--r-- 1 www-data www-data    0 Jul 12 05:29 .htdigest
-rw-r--r-- 1 www-data www-data    0 Jul 12 05:29 .htaccess
-rw-rw---- 1 www-data www-data  126 Jul 12 05:29 data.yaml
drwxr-xr-x 7 www-data www-data 4.0K Jul 12 05:29 .git
-rw-r--r-- 1 www-data www-data    0 Jul 12 05:29 last_read_access
drwxr-xr-x 3 www-data www-data 4.0K Jul 12 05:29 .
drwxr-xr-x 7 www-data root     4.0K Jul 12 05:36 ..


```

http://192.168.56.101/dudle/check.cgi
Your environment seems to be installed correctly!

Root: /var/www/dudle

root@dudle:/var/www# ls -la
total 16
drwxr-xr-x  4 root     root 4096 Jul 12 05:12 .
drwxr-xr-x 14 root     root 4096 Jul 12 04:31 ..
drwxr-xr-x  7 www-data root 4096 Jul 12 05:36 dudle

/etc/apache2/conf-available/dudle.conf

```
Alias /dudle /var/www/html/dudle
<Directory /var/www/html/dudle>
     SetEnv RUBYLIB /var/www/dudle/
     Options +ExecCGI
     AllowOverride All
     Order allow,deny
     Allow from all
</Directory>

```
/var/log/apache2/error.log
```

/var/www/dudle/dudle.rb:130:in `initialize': undefined method `name' for false:FalseClass (NoMethodError)
	from /var/www/dudle/TEST2/edit_columns.cgi:34:in `new'
	from /var/www/dudle/TEST2/edit_columns.cgi:34:in `<main>'
[Thu Jul 12 05:29:48.160570 2018] [cgid:error] [pid 1662:tid 140318712223488] [client 192.168.56.1:37720] End of script output before headers: edit_columns.cgi, referer: http://192.168.56.101/dudle/

```

Enabled Apache Modules:

```
# a2query -m
setenvif (enabled by maintainer script)
filter (enabled by maintainer script)
autoindex (enabled by maintainer script)
status (enabled by maintainer script)
alias (enabled by maintainer script)
auth_digest (enabled by site administrator)
cgid (enabled by site administrator)
reqtimeout (enabled by maintainer script)
negotiation (enabled by maintainer script)
deflate (enabled by maintainer script)
auth_basic (enabled by maintainer script)
mpm_event (enabled by maintainer script)
dir (enabled by maintainer script)
authz_core (enabled by maintainer script)
authn_file (enabled by maintainer script)
mime (enabled by maintainer script)
authz_user (enabled by maintainer script)
authz_host (enabled by maintainer script)
passenger (enabled by maintainer script)
authn_core (enabled by maintainer script)
env (enabled by maintainer script)
access_compat (enabled by maintainer script)
rewrite (enabled by site administrat
```or)


Software Versions:

```
ruby 2.5.1p57 
ruby-passenger 5.0.30-1build2
Apache: 2.4.29-1ubuntu4.2
gettext 0.19.8.1-6
potool 0.16-3
libapache2-mod-passenger 5.0.30-1build2

```

What did I wrong ?

**Comment by kellerben** [comment]
Can you give me the output of:
```sh
cd /var/www/dudle/TEST2/
git log
cat data.yaml
```

**Comment by chapinei** [comment]
Hi Benjamin! 

Since ds2k5 hasn't responded yet I think I'll quickly step in. I'm on a very similar setup (Apache2 on Ubuntu 18.04 Server) and I experience exactly the same issue.
I also receive a Internal Server Error message when creating a new poll. The error message in Apache's error.log is identical. Output from check.cgi tells me that everything is fine.

So, to answer your questions:
(1) Running "git log" in the directory of the newly created poll results in the following message: "fatal: your current branch 'master' does not have any commits yet". Running git log one level higher displays the Git history as expected. 
(2) data.yaml contains the following:
    # This is a dudle poll file
    --- !ruby/object:Poll
    name: TEST2
    head: !ruby/object:PollHead
      data: {}
    data: {}
    comment: []

If you have any idea how to fix this, please let us know. 

Cheers
Tobias

**Comment by kellerben** [comment]
there is a problem for the apache to execute git commit. Line 64-71 of the file vcs_git.rb were not executed during creation of the poll.
The callstack should be:
index.cgi:63
poll.rb:75
poll.rb:450
vcs_git.rb:64

maybe you can debug this while submitting the creation of a new poll?

**Comment by mguentner** [comment]
I did experience the same with Debian, Lighttpd + CGI. I also believe that #77, #95 are all related.

`git commit` does not work if `GIT_AUTHOR_NAME` etc. are not set

This is how I solved it:

```
$HTTP["host"] == "dudle.foo.bar" {
    server.document-root = "/var/www/dudle/"
    index-file.names = ( "index.cgi" )
    cgi.assign = ( ".cgi" => "/usr/bin/ruby" )
    setenv.add-environment = (
      "GIT_AUTHOR_NAME" => "Anon",
      "GIT_AUTHOR_EMAIL" => "anon@foo.bar",
      "GIT_COMMITTER_NAME" => "anon",
      "GIT_COMMITTER_EMAIL" => "anon@foo.bar"
    )
}
```

**Comment by chapinei** [comment]
Thanks for your help... and sorry for the late response. Today, I found some time to follow up on your suggestions. 

The git author and email address are set correctly for the user that runs apache, i.e. I can log in as this user and commit to git repositories without problems. For good measure, I added GIT_* to the .htaccess file but it didn't have any effect. 

Then I tried debugging vcs_git.rb. Despite not being a ruby wizard, I managed to extract the output of runcmd in vcs_git.rb: 
> Initialized empty Git repository in /var/www/html/dudle/TEST2/.git/
> 
> *** Please tell me who you are.
> 
> Run
>   git config --global user.email "you@example.com"
>   git config --global user.name "Your Name"
> 
> to set your account's default identity.
> Omit --global to set the identity only in this repository.
> 
> fatal: unable to auto-detect email address (got 'www-data@hostname.(none)')
> fatal: your current branch 'master' does not have any commits yet

So, looks like it is an issue with the git configuration after all. Then, I added the following to my VirtualHost config in Apache:
> SetEnv GIT_AUTHOR_NAME "http user"
> SetEnv GIT_AUTHOR_EMAIL "foo@example.org"
> SetEnv GIT_COMMITTER_NAME "GIT_AUTHOR_NAME"
> SetEnv GIT_COMMITTER_EMAIL "GIT_AUTHOR@EMAIL"

First, the output of runcmd looked good, but I still received the internal server error from apache. Then, I removed my weird debugging… and now it's working like a charm.

Thanks for your help!

Cheers
Tobias

**Comment by kellerben** [comment]
there is already a check in
d5eccb541f22ce0989a961434fc99999c84bd223/check.cgi#L79-81
